Cmd: demo.py
ExecutionDir: /src-nfs
Images:
  BaseImage: tensorflow/tensorflow
  GpuImage: kuberlab/gpu-monitoring:latest
  PSImage: tensorflow/tensorflow
MonitoringNamespace: {{ .monitoringNamespace }}
Requests:
  CPU: {{ .resources.requests.cpu }}
  CPULimit: {{ .resources.limits.cpu }}
  GPU: {{ .resources.GPU }}
  Memory: {{ .resources.requests.memory }}
  MemoryLimit: {{ .resources.limits.memory }}
  PsPods: {{ .resources.pods.ps }}
  WorkerPods: {{ .resources.pods.worker }}
Volumes:
- name: output
  isTrainLogDir: true
  mountPath: /training
  subPath: training
  nfs:
{{ toYaml .nfs | indent 4 }}
- name: github
  mountPath: /src
  gitRepo:
    repository: https://github.com/lsheiba/devol
- name: nfs
  mountPath: /src-nfs
  subPath: /devol
  nfs:
{{ toYaml .nfs | indent 4 }}
- name: lib
  isLibDir: true
  mountPath: /plib
  subPath: lib
  nfs:
{{ toYaml .nfs | indent 4 }}
